### ISSUE TITLE
Realtime classification

### ISSUE THREAD

**Issue by eighteight** [guillaume-chevalier/LSTM-Human-Activity-Recognition#10]
Hi!

Thanks for posting this code. Do you think this approach will work for realtime classification of the human activity?

**Comment by guillaume-chevalier** [comment]
The code can be exported to C++ with the TensorFlow library. Training may be long, but doing predictions is fast. This can run real-time if you already have at least 2.56 seconds of recorded signal available. For example, from the moment you start your app, you could have to wait 2.56 seconds only one time, then predictions could be real-time.

If this is too long, you could shorten the time window, but accuracy may (or may not?) decrease: to be tested.
