### ISSUE TITLE
Query regarding data collection

### ISSUE THREAD

**Issue by thanish** [guillaume-chevalier/LSTM-Human-Activity-Recognition#18]
HI @guillaume-chevalier , your code is very useful. I wanted to know if the collected data was from multiple users or from single user? and if it is from multiple users are all the users present in both train and test (overlap) or train and test has different users?

**Comment by guillaume-chevalier** [comment]
Quote from the [dataset's page on the UCI ML Repository](https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) and with interesting passages in bold: 
> The experiments have been carried out with **a group of 30 volunteers within an age bracket of 19-48 years**. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. **The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.**
