### ISSUE TITLE
live recognition activity

### ISSUE THREAD

**Issue by mahdiedst** [guillaume-chevalier/LSTM-Human-Activity-Recognition#28]
hello thanks for great github :+1: 
is this model capable of detecting and recognition activity from laptop's camera for live ?

**Comment by no-1ne** [comment]
Checkout  https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html
Powered by tf.js everything runs on the browser


Source code here https://github.com/tensorflow/tfjs-models/tree/master/posenet

**Comment by guillaume-chevalier** [comment]
This project doesn't use video.
