### ISSUE TITLE
Broken link in repo description

### ISSUE THREAD

**Issue by bencxs** [guillaume-chevalier/LSTM-Human-Activity-Recognition#4]
I've noticed that the link below found in the repository description is broken?

[https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones](https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

![2016-11-28_1432](https://cloud.githubusercontent.com/assets/19514983/20658524/8963be7a-b578-11e6-9df1-34bd57c9cf82.png)

**Comment by zhaoyu611** [comment]
yeah, maybe too many people try to download

**Comment by zaverichintan** [comment]
https://github.com/zaverichintan/HAR_prediction you can get the data here..

**Comment by bencxs** [comment]
@zaverichintan @zhaoyu611 Thanks!

**Comment by guillaume-chevalier** [comment]
The UCI website is up and running now.
